# Generated by Django 3.2.25 on 2024-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
